### ISSUE TITLE
Euphonic: v1.0

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#177]
First release version of Euphonic by end of July. Tasks:

- [x] Merge v1.0 features [normalise dos](https://github.com/pace-neutrons/Euphonic/issues/222) and [remove deprecations](https://github.com/pace-neutrons/Euphonic/issues/212) into master https://github.com/pace-neutrons/Euphonic/pull/231
- [x] Change default average_repeat_points to True https://github.com/pace-neutrons/Euphonic/issues/233
- [x] Drop Python 3.6 support https://github.com/pace-neutrons/Euphonic/issues/232

**Comment by rebeccafair** [comment]
It's out! https://github.com/pace-neutrons/Euphonic/releases/tag/v1.0.0
