### ISSUE TITLE
Euphonic: Brille Integration

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#179]
Users should be able to seamlessly use [Brille](https://github.com/brille/brille) from Euphonic for faster interpolation of phonon frequencies/eigenvectors. Tasks:

- [x] Debug Brille
  - [x] Close https://github.com/brille/brille/issues/63?
  - [x] Review https://github.com/brille/brille/pull/78
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/192
- [x] https://github.com/brille/brille/issues/86
- [x] Redo profiling after https://github.com/brille/brille/issues/86 completed
- [x] Update Euphonic https://github.com/pace-neutrons/Euphonic/pull/104
- [x] Update euphonic_sqw_models https://github.com/pace-neutrons/euphonic_sqw_models/pull/11
- [x] Update Horace-Euphonic-Interface https://github.com/pace-neutrons/horace-euphonic-interface/issues/1
- [x] Release Euphonic. Done in https://github.com/pace-neutrons/Euphonic/releases/v1.2.0
- [x] Release euphonic_sqw_models. Done in https://github.com/pace-neutrons/euphonic_sqw_models/releases/v1.1.0
- [x] Release horace-euphonic-interface. Done in https://github.com/pace-neutrons/horace-euphonic-interface/releases/v1.1.0
