### ISSUE TITLE
Euphonic: Powders

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#180]
Easy and efficient simulation of powders in Euphonic in addition to single crystals is important for many users. Required tasks:
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/187

Priorities from above discussion:
- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/195
- [ ] https://github.com/pace-neutrons/Euphonic/issues/214

We may get powder averaging for free if the following is completed:
- [ ] Generic projections in Horace https://github.com/pace-neutrons/Horace/issues/34
- [ ] #197

Worth investigating:
- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/165
- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/164
- [ ] https://github.com/pace-neutrons/Euphonic/issues/145

Old/outdated tasks:
- [x] Old overall powders plan https://github.com/pace-neutrons/Pace-Project-Plan/issues/25
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/163, duplicate of Euphonic 145 above
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/115
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/88
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/86

**Comment by ajjackson** [comment]
https://github.com/pace-neutrons/Euphonic/issues/145 is arguably a subset of https://github.com/pace-neutrons/Pace-Project-Plan/issues/163 : the former is _random_ jitter in the r-axis while the latter covers more systematic approaches.

**Comment by ajjackson** [comment]
Sobol sequences is still worth a look actually: Scipy offers a few quasi-random sequences and it wouldn't be much work to add them to the menu. https://docs.scipy.org/doc/scipy/reference/stats.qmc.html
