### ISSUE TITLE
Euphonic: Interfaces

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#181]
Euphonic already supports CASTEP and Phonopy but supporting reading from more codes would allow Euphonic to be useful to a wider audience. Tasks:

- [ ] Other interfaces?
- [ ] Quantum Espresso (may be able to get extra effort as a result of ASE interface)?
- [ ] ASE:
   - [x] Task breakdown: https://github.com/pace-neutrons/Pace-Project-Plan/issues/188
   - [ ] Merge https://gitlab.com/ase/ase/-/merge_requests/2576
   - [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/194
