### ISSUE TITLE
Euphonic: Anharmonicity

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#182]
Euphonic currently uses only harmonic lattice dynamics, but introducing anharmonicity could increase the range of systems that Euphonic can simulate accurately. Tasks:
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/189. Done, [Anharmonicity for Neutrons](https://stfc365.sharepoint.com/:b:/r/sites/PACEProject/Shared%20Documents/Euphonic/Development%20Roadmaps/Anharmonicity_for_neutrons.pdf?csf=1&web=1&e=SPuooH) document created, further tasks taken from https://github.com/pace-neutrons/Pace-Project-Plan/issues/189#issuecomment-1280788681
- [x] Identify candidate systems. MgO is a simple system with some experimental data in https://doi.org/10.1103/PhysRevB.99.220304
- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/193
- [ ] AJJ/KR to perform proof-of-concept import of renormalised harmonic phonons into Euphonic. (This may _Just Work™_ using Phonopy format as an intermediate, but likely some fiddling will be required.)
  - In principle this can be done using tutorial data or cheap force calculators, without waiting for item 1
- [ ] Obtain phonon lifetimes and apply to Euphonic spectrum as Lorentzian broadening. This depends on https://github.com/pace-neutrons/Euphonic/issues/240
- [ ] Deeper exploration of molecular dynamics sampling. This could act as validation of Lorentzian broadening, as well as provide a way to access anharmonic and multi-phonon contributions simultaneously.
