### ISSUE TITLE
Euphonic: Refinable Parameters

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#183]
Models never fit exactly to the experimental data, refining parameters in the model can improve this fit. It's not clear yet what parameters users want to fit and how. Tasks:

- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/190
- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/173
- [ ] https://github.com/pace-neutrons/Pace-Project-Plan/issues/191
