### ISSUE TITLE
Euphonic Calculations: Performance Optimisation: Preconditioning/Extrapolation of dynamic matrices

### ISSUE THREAD

**Issue by stfc-lam** [pace-neutrons/Pace-Project-Plan#22]

**Comment by DBJochym** [comment]
There should be an optimisation possible that takes advantage of the physical properties of dynamical matrices at nearby q-points. Three options have been identified for further investigation.
- Preconditioning
- Co-diagonalisation
- Sternheimer extrapolation
For all three, a test harness is needed to leverage existing Euphonic (and Brille) functionality in order to prototype and evaluate performance.

Note that this could include novel methods development.

- [ ] Set up test environment to validate coarse -> fine grid of q-points (See #70)
- [ ] Investigate/prototype preconditioning to accelerate diagonalisation of dynamical matrices, and benchmark (see #71)
- [ ] Investigate/prototype co-diagonalisation of pairs (sets?) of dynamical matrices, and benchmark (see #72)
- [ ] Investigate/prototype extrapolation of dynamical matrices to nearby q-points by use of a 1st-order Sternheimer equation, and benchmark (see #73)
- [ ] Report and make recommendations for adoption of methods into Euphonic (see #74)

**Comment by cmarooney-stfc** [comment]
Hi Dominik - Noticing that this is the parent task for #70-#74, and that #70 has been completed. I've consequently put this ticket into "In Progress", but can you tick off #70 as completed in the 5/2/20 comment serving as description? Also, do we have a plan for the set of tasks here - expected completion dates and so on? thanks CHris
