### ISSUE TITLE
Euphonic Calculations: Performance Optimisation

### ISSUE THREAD

**Issue by stfc-lam** [pace-neutrons/Pace-Project-Plan#77]
- ~pace-neutrons/Pace-Project-Plan/issues/19~Not really performance
- [x] pace-neutrons/Pace-Project-Plan/issues/20
- [x] pace-neutrons/Pace-Project-Plan/issues/21
- ~pace-neutrons/Pace-Project-Plan/issues/22~ Moved outside of this epic
- [x] pace-neutrons/Pace-Project-Plan/issues/23

**Comment by rebeccafair** [comment]
Closing as all sub-tasks have been either completed, closed, or moved
